name: Build, Push, and Deploy Docker Image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Get the short commit hash
      - name: Get short commit hash
        id: vars
        run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      # Step 5: Build and push the Docker image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            shirbenyosef1/my-app-image:latest
            shirbenyosef1/my-app-image:${{ env.COMMIT_HASH }}

      # Step 6: Install SSH client
      - name: Install SSH client
        run: sudo apt-get install -y openssh-client

      # Step 7: Add SSH private key
      - name: Add SSH private key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_PRIVATE_KEY }}

      # Step 8: SSH into EC2 instance and deploy the Docker image
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            # Pull the latest Docker image
            docker pull shirbenyosef1/my-app-image:latest
            
            # Run the new container
            docker run --rm shirbenyosef1/my-app-image:latest
          EOF
